### PR TITLE
Add Temporary Role Example

### PR DESCRIPTION
**Pull request by ocap-kirk**
Added the example of creating temporary roles using ABAC condtion sets via the API.

### CODE REVIEW

**Comment by orweis** [comment]
Love this!
1. I would call this "Time based roles" - while "temporary" literally has the word time in it - most people don't read it that way; and most PAM and JIT solutions use the term "time based"
2. I'd put this under best practices - and not under ABAC- to make it more prominent 
3. maybe add a link in ABAC design patterns as well ?

**Comment by ocap-kirk** [comment]
@filipermit @gemanor I'm going to need your help putting in the right place. I have no idea how the sidebar is rendered based on the current structure.

**Comment by ocap-kirk** [comment]
@orweis for your review

**Review by orweis — APPROVED** [review]

**Comment by orweis** [comment]
Approved 😁

**Pull request merged**
